from . import (LSTM, MICN, TCN, Autoformer, Crossformer, DLinear, ETSformer,
               FEDformer, FiLM, FreTS, Informer, InviTransformer, Koopa,
               LightTS, Nonstationary_Transformer, PatchTST, Pyraformer,
               Reformer, TiDE, TimesNet, Transformer, iFETransformer,
               iTransDecoder, iTransformer, iTransformerAdaHeader,
               iTransformerProj)

MODEL_DICT = {
    'TimesNet': TimesNet,
    'Autoformer': Autoformer,
    'Transformer': Transformer,
    'Nonstationary_Transformer': Nonstationary_Transformer,
    'DLinear': DLinear,
    'FEDformer': FEDformer,
    'Informer': Informer,
    'LightTS': LightTS,
    'Reformer': Reformer,
    'ETSformer': ETSformer,
    'PatchTST': PatchTST,
    'Pyraformer': Pyraformer,
    'MICN': MICN,
    'Crossformer': Crossformer,
    'FiLM': FiLM,
    'iTransformer': iTransformer,
    'InviTransformer': InviTransformer,
    'iTransformerProj': iTransformerProj,
    'iTransDecoder': iTransDecoder,
    'iFETransformer': iFETransformer,
    'Koopa': Koopa,
    'TiDE': TiDE,
    'LSTM': LSTM,
    'TCN': TCN,
    'FreTS': FreTS,
    'iTransformerAdaHeader': iTransformerAdaHeader,
}